# Generated by Django 2.1.3 on 2018-11-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDataModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip_codes', models.TextField(blank=True, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('street_address_zip', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('contact_title', models.TextField(blank=True, null=True)),
                ('contact_gender', models.TextField(blank=True, null=True)),
                ('actual_employee_size', models.IntegerField(blank=True, null=True)),
                ('employee_size_range', models.TextField(blank=True, null=True)),
                ('actual_sales_volume', models.IntegerField(blank=True, null=True)),
                ('sales_volume_range', models.TextField(blank=True, null=True)),
                ('primary_sic', models.IntegerField(blank=True, null=True)),
                ('primary_sic_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
