# Generated by Django 2.1.3 on 2018-11-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchdatamodel',
            table='searchdatamodel',
        ),
    ]
